# Generated by Django 4.2.23 on 2025-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='places/')),
                ('category', models.CharField(choices=[('Temple', 'Temple'), ('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('Monument', 'Monument'), ('Wildlife', 'Wildlife'), ('Other', 'Other')], max_length=30)),
                ('district', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=300)),
            ],
        ),
    ]
