# Generated by Django 3.2.24 on 2025-07-13 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0002_touristplace_created_at_touristplace_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='accommodation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='entry_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='how_to_reach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='nearby_attractions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='category',
            field=models.CharField(choices=[('Temple', 'Temple'), ('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('Monument', 'Monument'), ('Wildlife', 'Wildlife'), ('Waterfall', 'Waterfall'), ('Fort', 'Fort'), ('Garden', 'Garden'), ('Museum', 'Museum'), ('Other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.touristplace')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
