#!/usr/bin/env python
import os
import django
import random
from decimal import Decimal

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tamilnadu_tourism.settings')
django.setup()

from destinations.models import TouristPlace

# Sample data for 50 places
PLACES = [
    {
        'name': 'Brihadeeswarar Temple',
        'category': 'Temple',
        'district': 'Thanjavur',
        'short_description': 'A UNESCO World Heritage Site and one of the largest temples in India.',
        'detailed_description': 'Built by Raja Raja Chola I in the 11th century, this temple is a marvel of Dravidian architecture and a UNESCO World Heritage Site. The temple tower is among the tallest of its kind in the world.',
        'how_to_reach': 'Thanjavur is well connected by road and rail. The temple is about 2 km from Thanjavur railway station.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:30 PM, 4:00 PM to 8:30 PM',
        'nearby_attractions': 'Thanjavur Palace, Saraswathi Mahal Library',
        'accommodation': 'Plenty of hotels and guest houses in Thanjavur city.',
        'latitude': Decimal('10.7828'),
        'longitude': Decimal('79.1310'),
        'featured': True,
        'image': 'places/brihadeeswarar_temple_4.jpg',
    },
    {
        'name': 'Meenakshi Amman Temple',
        'category': 'Temple',
        'district': 'Madurai',
        'short_description': 'A historic Hindu temple located on the southern bank of the Vaigai River.',
        'detailed_description': 'Famed for its stunning architecture and towering gopurams, the Meenakshi Temple is dedicated to Goddess Meenakshi and Lord Sundareswarar.',
        'how_to_reach': 'Located in the heart of Madurai, easily accessible by road and rail.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free (special darshan tickets available)',
        'timings': '5:00 AM to 12:30 PM, 4:00 PM to 10:00 PM',
        'nearby_attractions': 'Thirumalai Nayakkar Mahal, Gandhi Museum',
        'accommodation': 'Numerous hotels and lodges in Madurai.',
        'latitude': Decimal('9.9195'),
        'longitude': Decimal('78.1191'),
        'featured': True,
        'image': 'places/meenakshi_temple.jpg',
    },
    {
        'name': 'Kanyakumari Beach',
        'category': 'Beach',
        'district': 'Kanyakumari',
        'short_description': 'The southernmost tip of India, famous for sunrise and sunset views.',
        'detailed_description': 'Kanyakumari Beach is where the Bay of Bengal, Indian Ocean, and Arabian Sea meet. It is known for its spectacular sunrise and sunset, especially on full moon days.',
        'how_to_reach': 'Kanyakumari is well connected by train and bus. The beach is close to the railway station.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': 'Open all day',
        'nearby_attractions': 'Vivekananda Rock Memorial, Thiruvalluvar Statue',
        'accommodation': 'Hotels and resorts available near the beach.',
        'latitude': Decimal('8.0883'),
        'longitude': Decimal('77.5385'),
        'featured': True,
        'image': 'places/kanyakumari_beach_5.jpg',
    },
    {
        'name': 'Ooty Botanical Gardens',
        'category': 'Garden',
        'district': 'The Nilgiris',
        'short_description': 'A beautiful garden in the hill station of Ooty.',
        'detailed_description': 'Spread over 55 acres, the Government Botanical Gardens in Ooty is home to thousands of exotic and indigenous plants, shrubs, ferns, and bonsai.',
        'how_to_reach': 'Ooty is accessible by road and the Nilgiri Mountain Railway. The gardens are 2 km from Ooty bus stand.',
        'best_time_to_visit': 'April to June, September to November',
        'entry_fee': 'INR 30 (adults), INR 15 (children)',
        'timings': '7:00 AM to 6:30 PM',
        'nearby_attractions': 'Ooty Lake, Doddabetta Peak',
        'accommodation': 'Hotels and homestays in Ooty.',
        'latitude': Decimal('11.4116'),
        'longitude': Decimal('76.7031'),
        'featured': True,
        'image': 'places/ooty_botanical_garden.jpg',
    },
    {
        'name': 'Kodaikanal Lake',
        'category': 'Hill Station',
        'district': 'Dindigul',
        'short_description': 'A star-shaped man-made lake in the heart of Kodaikanal.',
        'detailed_description': 'Kodaikanal Lake is a popular tourist spot for boating, cycling, and horse riding. The lake is surrounded by lush greenery and hills.',
        'how_to_reach': 'Kodaikanal is accessible by road from Madurai and Coimbatore. The lake is centrally located.',
        'best_time_to_visit': 'April to June, September to October',
        'entry_fee': 'Free (boating charges extra)',
        'timings': '6:00 AM to 5:00 PM',
        'nearby_attractions': 'Coaker’s Walk, Bryant Park',
        'accommodation': 'Hotels and resorts around the lake.',
        'latitude': Decimal('10.2381'),
        'longitude': Decimal('77.4892'),
        'featured': True,
        'image': 'places/kodaikanal_8.jpg',
    },
    # --- START OF NEW AUTHENTIC PLACES ---
    {
        'name': 'Ramanathaswamy Temple',
        'category': 'Temple',
        'district': 'Ramanathapuram',
        'short_description': 'A sacred Hindu temple on Rameswaram island, famous for its long corridors.',
        'detailed_description': 'Ramanathaswamy Temple is one of the twelve Jyotirlinga temples and a major pilgrimage site. Its corridors are the longest among all Hindu temples in India.',
        'how_to_reach': 'Rameswaram is connected by rail and road to major cities. The temple is 2 km from Rameswaram railway station.',
        'best_time_to_visit': 'October to April',
        'entry_fee': 'Free (special darshan tickets available)',
        'timings': '5:00 AM to 1:00 PM, 3:00 PM to 9:00 PM',
        'nearby_attractions': 'Dhanushkodi, Pamban Bridge',
        'accommodation': 'Hotels and lodges available in Rameswaram.',
        'latitude': Decimal('9.2881'),
        'longitude': Decimal('79.3174'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Mahabalipuram Shore Temple',
        'category': 'Monument',
        'district': 'Chengalpattu',
        'short_description': 'A UNESCO World Heritage Site on the Coromandel Coast.',
        'detailed_description': 'The Shore Temple is a structural temple built with blocks of granite, dating from the 8th century AD. It is part of the Group of Monuments at Mahabalipuram.',
        'how_to_reach': 'Mahabalipuram is 60 km from Chennai, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 40 (Indians), INR 600 (foreigners)',
        'timings': '6:00 AM to 6:00 PM',
        'nearby_attractions': 'Pancha Rathas, Arjuna’s Penance',
        'accommodation': 'Resorts and hotels in Mahabalipuram.',
        'latitude': Decimal('12.6170'),
        'longitude': Decimal('80.1994'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Yercaud Lake',
        'category': 'Hill Station',
        'district': 'Salem',
        'short_description': 'A serene lake in the Shevaroy hills, ideal for boating.',
        'detailed_description': 'Yercaud Lake is surrounded by gardens and woods, offering boating and a peaceful atmosphere in the hill station of Yercaud.',
        'how_to_reach': 'Yercaud is 30 km from Salem, accessible by road.',
        'best_time_to_visit': 'October to June',
        'entry_fee': 'Free (boating charges extra)',
        'timings': '9:00 AM to 5:30 PM',
        'nearby_attractions': 'Lady’s Seat, Pagoda Point',
        'accommodation': 'Hotels and resorts in Yercaud.',
        'latitude': Decimal('11.7753'),
        'longitude': Decimal('78.2096'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Mudumalai National Park',
        'category': 'Wildlife',
        'district': 'The Nilgiris',
        'short_description': 'A famous tiger reserve and wildlife sanctuary.',
        'detailed_description': 'Mudumalai is home to tigers, elephants, leopards, and many bird species. It is part of the Nilgiri Biosphere Reserve.',
        'how_to_reach': 'Accessible by road from Ooty (40 km) and Mysore (90 km).',
        'best_time_to_visit': 'February to June, September to December',
        'entry_fee': 'INR 30 (Indians), INR 300 (foreigners)',
        'timings': '6:00 AM to 6:00 PM',
        'nearby_attractions': 'Bandipur National Park, Masinagudi',
        'accommodation': 'Forest lodges and resorts nearby.',
        'latitude': Decimal('11.5983'),
        'longitude': Decimal('76.5856'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Courtallam Waterfalls',
        'category': 'Waterfall',
        'district': 'Tenkasi',
        'short_description': 'Known as the “Spa of South India”, famous for its medicinal water.',
        'detailed_description': 'Courtallam has nine waterfalls, each with unique charm. The water is believed to have medicinal properties due to the herbs in the Western Ghats.',
        'how_to_reach': 'Tenkasi is the nearest railway station (7 km). Buses available from Tirunelveli.',
        'best_time_to_visit': 'June to September (monsoon)',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 8:00 PM',
        'nearby_attractions': 'Five Falls, Old Courtallam',
        'accommodation': 'Hotels and lodges in Courtallam and Tenkasi.',
        'latitude': Decimal('8.9216'),
        'longitude': Decimal('77.2682'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Vellore Fort',
        'category': 'Fort',
        'district': 'Vellore',
        'short_description': 'A 16th-century fort with a moat and ancient temples.',
        'detailed_description': 'Vellore Fort is known for its grand ramparts, wide moat, and the Jalakandeswarar Temple inside. It also houses a church and a mosque.',
        'how_to_reach': 'Vellore is well connected by road and rail. The fort is in the city center.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'Free',
        'timings': '8:00 AM to 6:00 PM',
        'nearby_attractions': 'Golden Temple, Government Museum',
        'accommodation': 'Hotels and guest houses in Vellore.',
        'latitude': Decimal('12.9187'),
        'longitude': Decimal('79.1325'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Pichavaram Mangrove Forest',
        'category': 'Wildlife',
        'district': 'Cuddalore',
        'short_description': 'One of the world’s largest mangrove forests, ideal for boating.',
        'detailed_description': 'Pichavaram offers unique boat rides through mangrove channels and is a haven for birdwatchers.',
        'how_to_reach': 'Pichavaram is 15 km from Chidambaram, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 5 (entry), boating extra',
        'timings': '8:00 AM to 5:00 PM',
        'nearby_attractions': 'Chidambaram Nataraja Temple',
        'accommodation': 'Lodges and hotels in Chidambaram.',
        'latitude': Decimal('11.4281'),
        'longitude': Decimal('79.7747'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kolli Hills',
        'category': 'Hill Station',
        'district': 'Namakkal',
        'short_description': 'A scenic hill station known for its hairpin bends and Agaya Gangai Falls.',
        'detailed_description': 'Kolli Hills is famous for its natural beauty, trekking trails, and the Agaya Gangai waterfall.',
        'how_to_reach': 'Kolli Hills is 45 km from Namakkal, accessible by road.',
        'best_time_to_visit': 'February to December',
        'entry_fee': 'Free',
        'timings': 'Open all day',
        'nearby_attractions': 'Agaya Gangai Falls, Arapaleeswarar Temple',
        'accommodation': 'Resorts and cottages in Kolli Hills.',
        'latitude': Decimal('11.2250'),
        'longitude': Decimal('78.3200'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Thiruvannamalai Arunachaleswarar Temple',
        'category': 'Temple',
        'district': 'Tiruvannamalai',
        'short_description': 'A grand temple at the foot of Arunachala hill, famous for Karthigai Deepam.',
        'detailed_description': 'This ancient temple is dedicated to Lord Shiva and is one of the Pancha Bhoota Stalas, representing fire.',
        'how_to_reach': 'Tiruvannamalai is well connected by road and rail.',
        'best_time_to_visit': 'November (Karthigai Deepam), October to March',
        'entry_fee': 'Free',
        'timings': '5:30 AM to 12:30 PM, 3:30 PM to 9:30 PM',
        'nearby_attractions': 'Arunachala Hill, Ramana Ashram',
        'accommodation': 'Hotels and ashrams in Tiruvannamalai.',
        'latitude': Decimal('12.2253'),
        'longitude': Decimal('79.0747'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Hogenakkal Falls',
        'category': 'Waterfall',
        'district': 'Dharmapuri',
        'short_description': 'Often called the “Niagara of India”, famous for coracle rides.',
        'detailed_description': 'Hogenakkal Falls is a major tourist attraction with medicinal baths and boat rides in round coracles.',
        'how_to_reach': '46 km from Dharmapuri, accessible by road.',
        'best_time_to_visit': 'July to October',
        'entry_fee': 'INR 10 (entry), boating extra',
        'timings': '8:00 AM to 5:30 PM',
        'nearby_attractions': 'Pennagaram, Melagiri Hills',
        'accommodation': 'TTDC hotel and local lodges.',
        'latitude': Decimal('12.1122'),
        'longitude': Decimal('77.7750'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Gingee Fort',
        'category': 'Fort',
        'district': 'Viluppuram',
        'short_description': 'A massive fort complex known as the “Troy of the East”.',
        'detailed_description': 'Gingee Fort is spread over three hillocks and is one of the most impregnable forts in India.',
        'how_to_reach': '37 km from Villupuram, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 25 (Indians), INR 300 (foreigners)',
        'timings': '9:00 AM to 5:00 PM',
        'nearby_attractions': 'Rajagiri, Krishnagiri, Chandrayandurg',
        'accommodation': 'Lodges in Gingee and Villupuram.',
        'latitude': Decimal('12.2541'),
        'longitude': Decimal('79.4177'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kumbakonam Temples',
        'category': 'Temple',
        'district': 'Thanjavur',
        'short_description': 'A town famous for its cluster of ancient temples.',
        'detailed_description': 'Kumbakonam is known as the “temple town” with over 188 temples, including the famous Adi Kumbeswarar and Sarangapani temples.',
        'how_to_reach': 'Kumbakonam is well connected by rail and road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 4:00 PM to 9:00 PM',
        'nearby_attractions': 'Mahamaham Tank, Airavatesvara Temple',
        'accommodation': 'Hotels and lodges in Kumbakonam.',
        'latitude': Decimal('10.9629'),
        'longitude': Decimal('79.3887'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Pulicat Lake',
        'category': 'Wildlife',
        'district': 'Thiruvallur',
        'short_description': 'A large brackish water lake, famous for migratory birds.',
        'detailed_description': 'Pulicat Lake is the second largest brackish water lake in India and a haven for flamingos and other migratory birds.',
        'how_to_reach': '60 km from Chennai, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 6:00 PM',
        'nearby_attractions': 'Pulicat Bird Sanctuary, Dutch Cemetery',
        'accommodation': 'Lodges and guest houses in Pulicat.',
        'latitude': Decimal('13.4141'),
        'longitude': Decimal('80.3161'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Vivekananda Rock Memorial',
        'category': 'Monument',
        'district': 'Kanyakumari',
        'short_description': 'A monument on a rock island, accessible by ferry.',
        'detailed_description': 'Built in 1970, this memorial honors Swami Vivekananda and offers panoramic views of the sea.',
        'how_to_reach': 'Ferry service from Kanyakumari mainland.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'INR 20 (entry), INR 50 (ferry)',
        'timings': '7:00 AM to 5:00 PM',
        'nearby_attractions': 'Thiruvalluvar Statue, Kanyakumari Beach',
        'accommodation': 'Hotels and lodges in Kanyakumari.',
        'latitude': Decimal('8.0772'),
        'longitude': Decimal('77.5520'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Srivilliputhur Andal Temple',
        'category': 'Temple',
        'district': 'Virudhunagar',
        'short_description': 'A famous temple with a towering gopuram, symbol of Tamil Nadu government.',
        'detailed_description': 'The temple is dedicated to Andal, one of the twelve Alvars, and is known for its 192-foot tower.',
        'how_to_reach': 'Srivilliputhur is well connected by rail and road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 4:00 PM to 8:00 PM',
        'nearby_attractions': 'Grizzled Squirrel Wildlife Sanctuary',
        'accommodation': 'Lodges and hotels in Srivilliputhur.',
        'latitude': Decimal('9.5122'),
        'longitude': Decimal('77.6336'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Poompuhar Beach',
        'category': 'Beach',
        'district': 'Mayiladuthurai',
        'short_description': 'A historic beach town, once a major port of the Cholas.',
        'detailed_description': 'Poompuhar is known for its long beach, ancient history, and the annual Chitra Pournami festival.',
        'how_to_reach': 'Poompuhar is 24 km from Sirkazhi, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'Free',
        'timings': 'Open all day',
        'nearby_attractions': 'Silappathikara Art Gallery, Danish Fort',
        'accommodation': 'TTDC hotel and local lodges.',
        'latitude': Decimal('11.1442'),
        'longitude': Decimal('79.8497'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Vattakottai Fort',
        'category': 'Fort',
        'district': 'Kanyakumari',
        'short_description': 'A seaside fort with scenic views of the Bay of Bengal.',
        'detailed_description': 'Vattakottai Fort is a circular fort built in the 18th century, offering panoramic sea views.',
        'how_to_reach': '7 km from Kanyakumari, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '8:00 AM to 5:00 PM',
        'nearby_attractions': 'Kanyakumari Beach, Vivekananda Rock Memorial',
        'accommodation': 'Hotels and lodges in Kanyakumari.',
        'latitude': Decimal('8.1106'),
        'longitude': Decimal('77.5417'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kalrayan Hills',
        'category': 'Hill Station',
        'district': 'Kallakurichi',
        'short_description': 'A lesser-known hill station, ideal for trekking and nature lovers.',
        'detailed_description': 'Kalrayan Hills offer waterfalls, forests, and tribal villages, perfect for offbeat travel.',
        'how_to_reach': 'Kallakurichi is the nearest town, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': 'Open all day',
        'nearby_attractions': 'Periyar Falls, Gomukhi Dam',
        'accommodation': 'Forest rest houses and lodges.',
        'latitude': Decimal('11.7000'),
        'longitude': Decimal('78.7000'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kalakkad Mundanthurai Tiger Reserve',
        'category': 'Wildlife',
        'district': 'Tirunelveli',
        'short_description': 'A large tiger reserve in the Western Ghats.',
        'detailed_description': 'This reserve is home to tigers, elephants, leopards, and many endemic species of flora and fauna.',
        'how_to_reach': 'Ambasamudram is the nearest town, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'INR 20 (Indians), INR 200 (foreigners)',
        'timings': '6:00 AM to 6:00 PM',
        'nearby_attractions': 'Manimuthar Falls, Papanasam Dam',
        'accommodation': 'Forest rest houses and lodges.',
        'latitude': Decimal('8.6500'),
        'longitude': Decimal('77.4000'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Sankagiri Fort',
        'category': 'Fort',
        'district': 'Salem',
        'short_description': 'A historic fort with 14 fort walls, built by the Vijayanagar Empire.',
        'detailed_description': 'Sankagiri Fort is known for its strategic location and panoramic views.',
        'how_to_reach': '38 km from Salem, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 25',
        'timings': '9:00 AM to 5:00 PM',
        'nearby_attractions': 'Sankari Durg, Bhavani Sagar Dam',
        'accommodation': 'Lodges in Sankagiri and Salem.',
        'latitude': Decimal('11.4481'),
        'longitude': Decimal('77.8722'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kutralam Main Falls',
        'category': 'Waterfall',
        'district': 'Tenkasi',
        'short_description': 'The main waterfall in Courtallam, popular for herbal baths.',
        'detailed_description': 'Kutralam Main Falls is the largest of the Courtallam falls, attracting thousands during the monsoon.',
        'how_to_reach': '7 km from Tenkasi, accessible by road.',
        'best_time_to_visit': 'June to September',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 8:00 PM',
        'nearby_attractions': 'Five Falls, Old Courtallam',
        'accommodation': 'Hotels and lodges in Courtallam.',
        'latitude': Decimal('8.9216'),
        'longitude': Decimal('77.2682'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Guindy National Park',
        'category': 'Wildlife',
        'district': 'Chennai',
        'short_description': 'A rare national park within a city, home to blackbucks and deer.',
        'detailed_description': 'Guindy National Park is a green lung of Chennai, with a children’s park and snake park.',
        'how_to_reach': 'Located in Chennai, accessible by road and rail.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 20 (adults), INR 5 (children)',
        'timings': '9:00 AM to 5:30 PM (closed on Tuesdays)',
        'nearby_attractions': 'Snake Park, Anna University',
        'accommodation': 'Hotels in Chennai.',
        'latitude': Decimal('13.0108'),
        'longitude': Decimal('80.2340'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Sathanur Dam',
        'category': 'Other',
        'district': 'Tiruvannamalai',
        'short_description': 'A scenic dam with a crocodile park and gardens.',
        'detailed_description': 'Sathanur Dam is built across the Pennaiyar River and is a popular picnic spot.',
        'how_to_reach': '30 km from Tiruvannamalai, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 10',
        'timings': '8:00 AM to 5:00 PM',
        'nearby_attractions': 'Crocodile Park, Botanical Garden',
        'accommodation': 'Lodges in Tiruvannamalai.',
        'latitude': Decimal('12.2567'),
        'longitude': Decimal('78.9633'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Muttukadu Boat House',
        'category': 'Other',
        'district': 'Chengalpattu',
        'short_description': 'A popular water sports and boating destination near Chennai.',
        'detailed_description': 'Muttukadu offers rowing, water scooters, and windsurfing on the backwaters.',
        'how_to_reach': '36 km from Chennai, on East Coast Road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 10 (entry), boating extra',
        'timings': '9:00 AM to 6:00 PM',
        'nearby_attractions': 'DakshinaChitra, Covelong Beach',
        'accommodation': 'Resorts and hotels nearby.',
        'latitude': Decimal('12.8232'),
        'longitude': Decimal('80.2412'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Karaikudi Chettinad Mansions',
        'category': 'Other',
        'district': 'Sivaganga',
        'short_description': 'Famous for grand heritage mansions and unique cuisine.',
        'detailed_description': 'Karaikudi is the heart of Chettinad, known for its palatial homes, antique markets, and spicy food.',
        'how_to_reach': 'Karaikudi is well connected by rail and road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'Varies by mansion',
        'timings': '9:00 AM to 6:00 PM',
        'nearby_attractions': 'Athangudi Palace, Chettinad Museum',
        'accommodation': 'Heritage hotels and lodges.',
        'latitude': Decimal('10.0667'),
        'longitude': Decimal('78.7667'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Siruvani Waterfalls',
        'category': 'Waterfall',
        'district': 'Coimbatore',
        'short_description': 'A scenic waterfall with the sweetest water in India.',
        'detailed_description': 'Siruvani Waterfalls is surrounded by dense forests and is a popular picnic spot.',
        'how_to_reach': '35 km from Coimbatore, accessible by road.',
        'best_time_to_visit': 'June to October',
        'entry_fee': 'INR 50',
        'timings': '10:00 AM to 5:00 PM',
        'nearby_attractions': 'Siruvani Dam, Kovai Kutralam Falls',
        'accommodation': 'Hotels in Coimbatore.',
        'latitude': Decimal('11.0190'),
        'longitude': Decimal('76.7397'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Vandalur Zoo (Arignar Anna Zoological Park)',
        'category': 'Other',
        'district': 'Chengalpattu',
        'short_description': 'One of the largest zoos in South Asia.',
        'detailed_description': 'Vandalur Zoo houses over 2,500 animals and is a major attraction for families.',
        'how_to_reach': '31 km from Chennai, accessible by road and suburban train.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'INR 50 (adults), INR 20 (children)',
        'timings': '9:00 AM to 5:00 PM (closed on Tuesdays)',
        'nearby_attractions': 'Vandalur Reserve Forest',
        'accommodation': 'Hotels in Chennai and Vandalur.',
        'latitude': Decimal('12.8925'),
        'longitude': Decimal('80.0807'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Thanjavur Maratha Palace',
        'category': 'Monument',
        'district': 'Thanjavur',
        'short_description': 'A historic palace complex with art gallery and Saraswathi Mahal Library.',
        'detailed_description': 'The palace was built by the Marathas and Nayaks and houses a museum, library, and art gallery.',
        'how_to_reach': 'Located in Thanjavur city, accessible by road and rail.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'INR 50',
        'timings': '9:00 AM to 5:30 PM',
        'nearby_attractions': 'Brihadeeswarar Temple, Schwartz Church',
        'accommodation': 'Hotels in Thanjavur.',
        'latitude': Decimal('10.7867'),
        'longitude': Decimal('79.1378'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Kanchipuram Temples',
        'category': 'Temple',
        'district': 'Kanchipuram',
        'short_description': 'Known as the “City of Thousand Temples”.',
        'detailed_description': 'Kanchipuram is famous for its ancient temples like Ekambareswarar, Kailasanathar, and Kamakshi Amman.',
        'how_to_reach': 'Kanchipuram is well connected by road and rail.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 4:00 PM to 8:00 PM',
        'nearby_attractions': 'Silk Saree Weaving Centers',
        'accommodation': 'Hotels and lodges in Kanchipuram.',
        'latitude': Decimal('12.8342'),
        'longitude': Decimal('79.7036'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Palaruvi Waterfalls',
        'category': 'Waterfall',
        'district': 'Tirunelveli',
        'short_description': 'A beautiful waterfall on the Tamil Nadu-Kerala border.',
        'detailed_description': 'Palaruvi means “stream of milk” and is a popular picnic spot, especially during the monsoon.',
        'how_to_reach': '75 km from Tirunelveli, accessible by road.',
        'best_time_to_visit': 'June to September',
        'entry_fee': 'INR 25',
        'timings': '8:00 AM to 5:00 PM',
        'nearby_attractions': 'Thenmala Dam, Courtallam Falls',
        'accommodation': 'Lodges in Palaruvi and Thenmala.',
        'latitude': Decimal('8.9600'),
        'longitude': Decimal('77.1000'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Chidambaram Nataraja Temple',
        'category': 'Temple',
        'district': 'Cuddalore',
        'short_description': 'A major Shaivite temple dedicated to Lord Nataraja (Shiva as the cosmic dancer).',
        'detailed_description': 'Chidambaram Temple is an architectural marvel and a major pilgrimage site for Hindus.',
        'how_to_reach': 'Chidambaram is well connected by rail and road.',
        'best_time_to_visit': 'December to February',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 5:00 PM to 10:00 PM',
        'nearby_attractions': 'Pichavaram Mangroves, Thillai Kali Temple',
        'accommodation': 'Hotels and lodges in Chidambaram.',
        'latitude': Decimal('11.3991'),
        'longitude': Decimal('79.6937'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Dhanushkodi',
        'category': 'Other',
        'district': 'Ramanathapuram',
        'short_description': 'A ghost town at the tip of Rameswaram island.',
        'detailed_description': 'Dhanushkodi was destroyed in the 1964 cyclone and is now a popular tourist spot for its haunting beauty and mythological significance.',
        'how_to_reach': '18 km from Rameswaram, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 6:00 PM',
        'nearby_attractions': 'Ramanathaswamy Temple, Pamban Bridge',
        'accommodation': 'Hotels in Rameswaram.',
        'latitude': Decimal('9.2722'),
        'longitude': Decimal('79.4786'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Masilamani Nathar Temple',
        'category': 'Temple',
        'district': 'Nagapattinam',
        'short_description': 'A unique temple built in 1306, partly submerged by the sea.',
        'detailed_description': 'This temple is a blend of Chinese and Tamil architecture and is located on the Bay of Bengal coast.',
        'how_to_reach': '20 km from Nagapattinam, accessible by road.',
        'best_time_to_visit': 'November to February',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 4:00 PM to 8:00 PM',
        'nearby_attractions': 'Velankanni Church, Nagore Dargah',
        'accommodation': 'Lodges in Nagapattinam and Tranquebar.',
        'latitude': Decimal('11.0272'),
        'longitude': Decimal('79.8583'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
    {
        'name': 'Vellimalai Murugan Temple',
        'category': 'Temple',
        'district': 'Kanyakumari',
        'short_description': 'A hilltop temple dedicated to Lord Murugan.',
        'detailed_description': 'Vellimalai is one of the six abodes of Lord Murugan and offers panoramic views of the Western Ghats.',
        'how_to_reach': '50 km from Nagercoil, accessible by road.',
        'best_time_to_visit': 'October to March',
        'entry_fee': 'Free',
        'timings': '6:00 AM to 12:00 PM, 4:00 PM to 8:00 PM',
        'nearby_attractions': 'Padmanabhapuram Palace, Thirparappu Falls',
        'accommodation': 'Lodges in Vellimalai and Nagercoil.',
        'latitude': Decimal('8.3000'),
        'longitude': Decimal('77.3500'),
        'featured': False,
        'image': 'places/placeholder.jpg',
    },
]

# Add places to the database
for place in PLACES:
    obj, created = TouristPlace.objects.get_or_create(
        name=place['name'],
        defaults={
            'category': place['category'],
            'district': place['district'],
            'short_description': place['short_description'],
            'detailed_description': place['detailed_description'],
            'how_to_reach': place['how_to_reach'],
            'best_time_to_visit': place['best_time_to_visit'],
            'entry_fee': place['entry_fee'],
            'timings': place['timings'],
            'nearby_attractions': place['nearby_attractions'],
            'accommodation': place['accommodation'],
            'latitude': place['latitude'],
            'longitude': place['longitude'],
            'featured': place['featured'],
            'image': place['image'],
        }
    )
    if created:
        print(f"Added: {place['name']}")
    else:
        print(f"Already exists: {place['name']}")

print("Sample data insertion complete.") 